Repository runelite/runelite.net, pull requests merged in 2018-04, with the labels that each got.

#41 Improve consistency of the language text in data/features.js
  src/_data/features.js
Labels: enhancement

#42 Don't hydrate website when pre-rendered
  .travis.yml
  package-lock.json
  package.json
  src/index.js
Labels: bug

#45 Add 1.3.3 post
  public/img/blog/1.3.3-Release/banktags.png
  public/img/blog/1.3.3-Release/indicators.png
  public/img/blog/1.3.3-Release/shiftclick.gif
  src/_posts/2018-04-05-1.3.3-Release.md
Labels: blog-post

#46 Add features from 1.3.3 snapshot
  public/img/features/banktags.png
  public/img/features/shiftclick.png
  src/_data/features.js
Labels: enhancement
