Repository runelite/runelite.net, pull requests merged in 2018-10, with the labels that each got.

#125 Validate generated XML during build process
  config-overrides.js
  package-lock.json
  package.json
Labels: enhancement

#126 Add 1.4.21 Release post
  public/img/blog/1.4.21-Release/2005-chat-background.gif
  public/img/blog/1.4.21-Release/bank-tag-tabs-intro.gif
  public/img/blog/1.4.21-Release/grand-exchange-search-before-after.gif
  public/img/blog/1.4.21-Release/master-three-step-cryptic-clue-full.png
  public/img/blog/1.4.21-Release/master-three-step-cryptic-clue-partial.png
  public/img/blog/1.4.21-Release/recolored-split-private-chat-to-from.png
  public/img/blog/1.4.21-Release/xp-globes-default-skill-color.png
  public/img/blog/1.4.21-Release/xp-globes-progress-overlay.png
  src/_posts/2018-10-11-10-00-1.4.21-Release.md
Labels: blog-post

#129 Make XP tracker fetching run in parallel
  src/modules/runelite.js
Labels: enhancement

#130 Sort XP tracker parallel entries by date
  src/modules/runelite.js
Labels: bug

#132 Fix start/end date xp tracker substraction
  src/routes/xp-show.js
Labels: bug

#133 Cleanup XP tracker code a bit
  src/modules/runelite.js
  src/routes/xp-show.js
Labels: enhancement

#134 Replace chartist with Recharts
  package-lock.json
  package.json
  src/routes/xp-show.css
  src/routes/xp-show.js
Labels: enhancement

#128 Add /tag/show/:csv for showing tag tab
  src/components/app.css
  src/components/app.js
  src/components/navigation.js
  src/components/tooltip.css
  src/modules/index.js
  src/modules/runelite.js
  src/modules/tag.js
  src/routes/tag-show.js
  src/routes/tag.css
  src/routes/tag.js
Labels: enhancement

#136 Replace now.sh integration with Heroku
  app.json
  config-overrides.js
  now.json
Labels: enhancement

#138 Move social icons at right and remove descriptions
  src/_data/links.js
  src/components/navigation.js
Labels: enhancement

#140 Add SCSS support, remove rounded corners, fix layout issues
  app.json
  config-overrides.js
  package-lock.json
  package.json
  src/components/app.css
  src/components/app.js
  src/components/app.scss
  src/components/hero.css
  src/components/navigation.css
  src/components/navigation.js
  src/routes/xp-show.js
Labels: bug, enhancement

#144 Add 1.4.23 Release post
  public/img/blog/1.4.23-Release/clue-tag-search.gif
  public/img/blog/1.4.23-Release/loot-tracker-hiding-ignored-items.gif
  public/img/blog/1.4.23-Release/loot-tracker-ignored-tooltip.png
  public/img/blog/1.4.23-Release/loot-tracker-toggling-items.gif
  public/img/blog/1.4.23-Release/poh-incense-burner-timers.gif
  public/img/blog/1.4.23-Release/twitch.png
  src/_posts/2018-10-25-10-00-1.4.23-Release.md
Labels: blog-post

#145 #127 Fixes build issues, fixes dropdown issues
  README.md
  package.json
  src/components/app.scss
Labels: bug

#146 Add support for displaying variation tags
  src/routes/tag-show.js
Labels: enhancement

#149 Remove Heroku stuff, switch to 0 config netlify
  app.json
  package-lock.json
  package.json
Labels: enhancement
