Repository runelite/runelite.net, pull requests merged in 2018-09, with the labels that each got.

#100 More prerendering, cleanup
  .travis.yml
  README.md
  package.json
  rollup.config.js
  src/blog.js
  src/index.js
Labels: enhancement

#101 Add back missing /dicord link and fix :cat: background size
  src/routes/index.js
  src/routes/not-found.js
Labels: bug

#102 Move from router5 to preact-router
  package-lock.json
  package.json
  src/components/app.css
  src/components/app.js
  src/components/link.js
  src/components/navigation.js
  src/components/provider.js
  src/components/redirect.js
  src/index.js
  src/middleware/router-middleware.js
  src/modules/runelite.js
  src/router.js
  src/routes/blog.js
  src/routes/home.js
  src/routes/index.js
  src/routes/not-found.js
  src/routes/xp-show.js
  src/store.js
Labels: enhancement

#103 Make code-splitting work correct with c-r-a
  .eslintrc
  .gitignore
  .travis.yml
  config-overrides.js
  generate-feed.js
  package-lock.json
  package.json
  public/index.html
  rollup.config.js
  src/api.js
  src/blog.js
  src/components/app.css
  src/components/app.js
  src/components/async.js
  src/components/loader.css
  src/components/loader.js
  src/components/navigation.css
  src/components/navigation.js
  src/index.js
  src/routes/blog-show.js
  src/routes/blog.js
  src/routes/home.js
  src/store.js
Labels: enhancement

#105 Prepare for now.sh support
  config-overrides.js
  now.json
  package-lock.json
  package.json
Labels: enhancement

#106 Replace moment.js with day.js, make chart.js continuosly update
  package-lock.json
  package.json
  src/modules/runelite.js
  src/routes/xp-show.js
Labels: enhancement

#108 Switch from chart.js to chartist, redesign xp tracker
  package-lock.json
  package.json
  src/_data/skills.js
  src/components/navigation.js
  src/modules/runelite.js
  src/routes/xp-show.js
Labels: enhancement

#104 Add Twitter link to homepage
  .gitignore
  src/_data/links.js
  src/components/navigation.js
Labels: enhancement

#109 Add 1.4.16 release blog post
  public/img/blog/1.4.16-Release/layoutable-runescape-widgets.gif
  public/img/blog/1.4.16-Release/top-center-snap-point.gif
  src/_posts/2018-09-06-10-00-1.4.16-Release.md
Labels: blog-post

#113 Move generate-feed to webpack plugin
  config-overrides.js
  generate-feed.js
  package-lock.json
  package.json
  public/atom.html
Labels: enhancement

#114 Simplify redux modules
  config-overrides.js
  package-lock.json
  package.json
  src/modules/app.js
  src/modules/git.js
  src/modules/navigation.js
  src/modules/runelite.js
  src/routes/home.js
  src/routes/xp-show.js
Labels: enhancement

#117 Add 1.4.17 release blog post
  public/img/blog/1.4.17-Release/grouped-loot-tracker.gif
  public/img/blog/1.4.17-Release/home-minigame-teleport-timers.png
  public/img/blog/1.4.17-Release/minigame-tooltips.png
  public/img/blog/1.4.17-Release/quest-tooltips.png
  src/_posts/2018-09-13-10-00-1.4.17-Release.md
Labels: blog-post

#118 Add 1.4.18 post
  public/img/blog/1.4.18-Release/virtuallevels.png
  public/img/blog/1.4.18-Release/wintertodt1.png
  public/img/blog/1.4.18-Release/wintertodt2.png
  src/_posts/2018-09-20-10-00-1.4.18-Release.md
Labels: blog-post

#119 Fix links for homepage features
  src/routes/home.js
Labels: bug

#122 Add 1.4.19 Release post
  public/img/blog/1.4.19-Release/bagame.png
  public/img/blog/1.4.19-Release/bawave.png
  public/img/blog/1.4.19-Release/buylimits.png
  src/_posts/2018-09-27-10-00-1.4.19-Release.md
Labels: blog-post
