Repository runelite/runelite.net, pull requests merged in 2019-02, with the labels that each got.

#177 Add 1.5.11 blog post
  public/img/blog/1.5.11-Release/discord-join.png
  public/img/blog/1.5.11-Release/party-overlay.png
  public/img/blog/1.5.11-Release/ping.gif
  public/img/blog/1.5.11-Release/tilemap.png
  src/_posts/2019-02-07-10-00-1.5.11-Release.md
Labels: blog-post

#178 Use SCSS variables for theming the website
  src/components/_variables.scss
  src/components/app.scss
  src/routes/xp-show.css
  src/routes/xp-show.js
Labels: enhancement

#181 Fix react-app-rewired and update dependencies
  .babelrc
  config-overrides.js
  package-lock.json
  package.json
  src/_posts/2019-02-07-10-00-1.5.11-Release.md
  src/modules/git.js
  src/modules/runelite.js
  src/routes/home.js
Labels: bug

#183 Split RuneLite module to smaller modules
  src/modules/index.js
  src/modules/item.js
  src/modules/runelite.js
  src/modules/xp.js
  src/routes/tag-show.js
  src/routes/xp-show.js
Labels: enhancement

#184 Cleanup redux modules code (automatically dispatch start/stop loading and use better naming for API lookups and selectors)
  src/components/app.js
  src/middleware/thunk-middleware.js
  src/modules/git.js
  src/modules/item.js
  src/modules/runelite.js
  src/modules/xp.js
  src/routes/home.js
  src/routes/tag-show.js
  src/routes/xp-show.js
Labels: enhancement

#185 Add prepare HOC and use it in routes
  src/components/prepare.js
  src/routes/gh-auth-code.js
  src/routes/home.js
  src/routes/tag-show.js
  src/routes/tag.js
  src/routes/xp-show.js
Labels: enhancement

#186 Add 1.5.12 post
  public/img/blog/1.5.12-Release/player-indicator-config.png
  public/img/blog/1.5.12-Release/player-indicator.gif
  public/img/blog/1.5.12-Release/poison-infobox.png
  public/img/blog/1.5.12-Release/poison.png
  public/img/blog/1.5.12-Release/venom-infobox.png
  public/img/blog/1.5.12-Release/wiki-lookup.gif
  public/img/blog/1.5.12-Release/wiki-quest.gif
  public/img/blog/1.5.12-Release/wiki-search.gif
  src/_posts/2019-02-14-10-00-1.5.12-Release.md
Labels: blog-post

#187 Add support for Linux platform detection
  src/components/hero.js
Labels: feature-request

#188 Add button for Linux64 AppImage download and 1.6.2 launcher release downloads
  src/_data/hero.js
Labels: feature-request

#189 Use fixed-width FontAwesome icons for downloads
  src/_data/hero.js
Labels: enhancement

#191 Add `skip: true` blog metadata that skips home page display
  README.md
  src/blog.js
Labels: feature-request

#192 Remove type=button from website button links
  src/components/app.scss
  src/components/hero.js
Labels: bug

#194 Add 1.5.13 Release post
  public/img/blog/1.5.13-Release/agility-shortcut-level-colors.png
  public/img/blog/1.5.13-Release/item-charge-infoboxes.gif
  public/img/blog/1.5.13-Release/pm-cycling.gif
  src/_posts/2019-02-21-10-00-1.5.13-Release.md
Labels: blog-post

#196 Add RSS feed link to footer
  src/components/footer.js
  src/util.js
Labels: enhancement

#198 Handle missing blog posts correctly
  src/blog.js
  src/components/app.js
  src/components/not-found.js
  src/routes/blog-show.js
Labels: bug

#180 Add OAuth authentication support
  package-lock.json
  package.json
  public/img/numbers.png
  src/components/app.js
  src/components/app.scss
  src/components/meta.js
  src/components/navigation.js
  src/index.js
  src/modules/account.js
  src/modules/config.js
  src/modules/ge.js
  src/modules/git.js
  src/modules/index.js
  src/modules/loot.js
  src/modules/session.js
  src/routes/account.js
  src/routes/account/grand-exchange.js
  src/routes/account/home.js
  src/routes/account/loot-tracker.css
  src/routes/account/loot-tracker.js
  src/routes/home.js
  src/routes/loading.js
  src/routes/xp-show.css
  src/routes/xp-show.js
  src/store.js
  src/util.js
Labels: feature-request

#199 Make blog post URLs case insensitive
  src/blog.js
  src/routes/blog.js
Labels: bug

#200 Properly show selected account in /account/home
  src/routes/account.js
Labels: bug

#201 Fix not-found spelling and missing punctuation
  src/components/not-found.js
Labels: enhancement

#202 Focus OAuth tab after opening it
  src/modules/account.js
Labels: enhancement

#203 Improve slayer task display in account/home
  src/routes/account/home.js
Labels: enhancement

#204 Add boss images to boss task display in account/home
  src/routes/account/home.js
Labels: enhancement

#205 Fix Deranged Archaeologist boss icon
  src/routes/account/home.js
Labels: bug

#206 Add NotFound handling to account/ and xp/show pages
  src/routes/account.js
  src/routes/xp-show.js
Labels: enhancement

#207 Extract dangerouslySetInnerHtml to separate component
  src/routes/blog-show.js
Labels: bug

#208 Lock package.json versions
  README.md
  package-lock.json
  package.json
Labels: enhancement

#209 Bump Bootstrap to 4.3.1
  package-lock.json
  package.json
Labels: security

#210 Add 1.5.14 post
  public/img/blog/1.5.14-Release/account.png
  public/img/blog/1.5.14-Release/ge.png
  public/img/blog/1.5.14-Release/import.png
  public/img/blog/1.5.14-Release/loot.png
  public/img/blog/1.5.14-Release/orbs.png
  src/_posts/2019-02-28-10-00-1.5.14-Release.md
Labels: blog-post

#212 Put personal best before kill count
  src/routes/account/home.js
Labels: enhancement
