Repository runelite/runelite.net, pull requests merged in 2019-10, with the labels that each got.

#258 Fix: JSON exports reach maximum length and download fails
  src/routes/account.js
Labels: bug

#261 Website rework
  package.json
  public/img/carousel/1.png
  public/img/carousel/2.png
  public/img/carousel/3.png
  public/img/ge_bought.png
  public/img/ge_sold.png
  public/img/runelite_logo_transparent.png
  src/_data/hero.js
  src/components/app.js
  src/components/app.scss
  src/components/commit.js
  src/components/feature.js
  src/components/feature.scss
  src/components/footer.js
  src/components/hero.css
  src/components/hero.js
  src/components/layout.css
  src/components/layout.scss
  src/components/loader.css
  src/components/navigation.css
  src/components/navigation.js
  src/components/search-bar.css
  src/components/search-bar.js
  src/routes/account.js
  src/routes/account.scss
  src/routes/account/grand-exchange.css
  src/routes/account/grand-exchange.js
  src/routes/account/home.js
  src/routes/account/loot-tracker.css
  src/routes/account/loot-tracker.js
  src/routes/blog-show.js
  src/routes/blog.js
  src/routes/blog.scss
  src/routes/features.css
  src/routes/features.js
  src/routes/gh-auth-code.js
  src/routes/gh-auth-code.scss
  src/routes/home.js
  src/routes/home.scss
  src/routes/loading.js
  src/routes/loading.scss
  src/routes/logged-in.js
  src/routes/logged-in.scss
  src/routes/tag-show.js
  src/routes/tag.css
  src/routes/tag.js
  src/routes/xp-show.js
  src/routes/xp-show.scss
Labels: feature-request

#264 Add 1.5.36 post
  public/img/blog/1.5.36-Release/random.png
  src/_posts/2019-10-17-10-00-1.5.36-Release.md
Labels: blog-post

#222 Updated Preact to v10 rc
  .gitignore
  config-overrides.js
  package-lock.json
  package.json
  src/components/app.js
  src/components/hero.js
  src/index.js
  src/routes/account.js
  src/routes/account/grand-exchange.js
  src/routes/account/home.js
  src/routes/account/loot-tracker.js
  src/routes/home.js
  src/routes/tag-show.js
  src/routes/tag.js
  src/routes/xp-show.js
Labels: enhancement

#265 xptracker: Show total xp/ranks only when 'overall' is selected
  .babelrc
  src/routes/xp-show.js
Labels: enhancement

#267 Use redirect generator for /discord redirect
  config-overrides.js
  redirect.js
  src/components/app.js
Labels: enhancement

#268 Remove unused git repository fetching
  src/components/app.js
  src/components/navigation.js
  src/modules/git.js
Labels: enhancement

#266 Switch to Fragments from empty divs and utilize Bootstrap
  src/components/app.scss
  src/components/async.js
  src/components/commit.js
  src/components/feature.js
  src/routes/account/grand-exchange.js
  src/routes/account/home.js
  src/routes/account/loot-tracker.js
  src/routes/gh-auth-code.js
  src/routes/home.js
  src/routes/loading.js
  src/routes/logged-in.js
  src/routes/tag-show.js
  src/routes/tag.js
  src/routes/xp-show.js
Labels: enhancement

#269 Switch to bootstrap.json for getting latest release
  src/index.js
  src/modules/account.js
  src/modules/bootstrap.js
  src/modules/config.js
  src/modules/ge.js
  src/modules/git.js
  src/modules/index.js
  src/modules/item.js
  src/modules/loot.js
  src/modules/xp.js
  src/routes/account/grand-exchange.js
  src/routes/account/home.js
  src/routes/account/loot-tracker.js
  src/routes/home.js
  src/routes/tag-show.js
  src/routes/xp-show.js
Labels: enhancement

#270 Fix git module action exports
  src/modules/git.js
Labels: bug

#272 Add back fetching of RL version before each RL request
  src/routes/account/grand-exchange.js
  src/routes/account/home.js
  src/routes/account/loot-tracker.js
  src/routes/tag-show.js
  src/routes/xp-show.js
Labels: bug

#273 loot tracker: add prices
  src/modules/index.js
  src/modules/loot.js
  src/modules/prices.js
  src/routes/account/loot-tracker.js
Labels: feature-request

#274 Add 1.5.37 post
  public/img/blog/1.5.37-Release/sliders.gif
  src/_posts/2019-10-30-10-00-1.5.37-Release.md
Labels: blog-post

#275 Update 1.5.37 Release post
  src/_posts/2019-10-30-10-00-1.5.37-Release.md
Labels: blog-post
