Repository runelite/runelite.net, pull requests merged in 2019-11, with the labels that each got.

#278 Fix homepage header display on mobile devices
  src/components/hero.css
  src/routes/account/loot-tracker.js
  src/util.js
Labels: bug

#276 Use /discord link for Discord invites in navbar
  redirect.js
  src/_data/links.js
  src/components/navigation.js
Labels: enhancement

#280 Fix 1.5.40 release post spelling
  src/_posts/2019-11-14-10-00-1.5.40-Release.md
Labels: blog-post
