Repository runelite/runelite.net, pull requests merged in 2020-11, with the labels that each got.

#378 Add plugin hub sorting based on updated and created time
  src/modules/plugin-hub.js
  src/routes/plugin-hub.js
Labels: feature-request

#381 Add sorting for installed plugins
  src/modules/plugin-hub.js
  src/routes/plugin-hub.js
Labels: feature-request

#382 Fix safari hover bug
  src/components/tooltip.css
  src/routes/account.scss
Labels: bug

#383 Add 1.6.31 post
  public/img/blog/1.6.31-Release/gpu-colorblind-deuteranope.png
  public/img/blog/1.6.31-Release/gpu-colorblind-protanope.png
  public/img/blog/1.6.31-Release/gpu-colorblind-tritanope.png
  public/img/blog/1.6.31-Release/merch-store.png
  public/img/blog/1.6.31-Release/new-status-bars.png
  src/_posts/2020-11-11-10-00-1.6.31-Release.md
Labels: blog-post
