Repository runelite/runelite.net, pull requests merged in 2020-07, with the labels that each got.

#338 Try to get prices for noted items
  src/modules/loot.js
  src/routes/account/loot-tracker.js
Labels: bug

#282 Update loot tracker to sort drops by highest value
  src/modules/loot.js
  src/routes/account/loot-tracker.js
Labels: feature-request

#339 Make tooltips consistent between all pages
  src/components/tooltip.css
  src/routes/account/loot-tracker.js
  src/routes/account/tags.js
  src/routes/tag.css
Labels: enhancement

#340 Make spacing in loot tracker consistent with client
  src/routes/account/loot-tracker.js
Labels: bug

#342 Add 1.6.22 post
  public/img/blog/1.6.22-Release/npc-indicators-tag-all.png
  public/img/blog/1.6.22-Release/npc-indicators-untag-all.png
  public/img/blog/1.6.22-Release/slayer-multikills.png
  src/_posts/2020-07-16-10-00-1.6.22-Release.md
Labels: blog-post

#343 Apply margin and border only to /pulse list group item
  src/components/app.scss
  src/routes/pulse.js
  src/routes/pulse.scss
Labels: bug

#344 Add 1.6.23 post
  public/img/blog/1.6.23-Release/bank-tag-no-separators-value-header.png
  src/_posts/2020-07-23-10-00-1.6.23-Release.md
Labels: blog-post
