Repository runelite/runelite.net, pull requests merged in 2020-09, with the labels that each got.

#356 Align tags left instead of center
  src/routes/account/tags.js
  src/routes/tag-show.js
Labels: enhancement

#357 Add farming tracker
  config-overrides.js
  package-lock.json
  package.json
  public/atom.html
  src/markdown-loader.js
  src/modules/time-tracking.js
  src/modules/timetracking/Autoweed.js
  src/modules/timetracking/BirdHouse.js
  src/modules/timetracking/BirdHouseData.js
  src/modules/timetracking/BirdHouseSpace.js
  src/modules/timetracking/BirdHouseState.js
  src/modules/timetracking/BirdHouseTracker.js
  src/modules/timetracking/CropState.js
  src/modules/timetracking/FarmingPatch.js
  src/modules/timetracking/FarmingRegion.js
  src/modules/timetracking/FarmingTracker.js
  src/modules/timetracking/FarmingWorld.js
  src/modules/timetracking/ItemID.js
  src/modules/timetracking/NullItemID.js
  src/modules/timetracking/PatchImplementation.js
  src/modules/timetracking/PatchPrediction.js
  src/modules/timetracking/PatchState.js
  src/modules/timetracking/Tab.js
  src/modules/timetracking/VarPlayer.js
  src/modules/timetracking/Varbits.js
  src/routes/account.js
  src/routes/account/loot-tracker.js
  src/routes/account/time-tracking.js
Labels: feature-request

#358 Show account selector in time tracking panel
  src/routes/account.js
Labels: bug

#359 Add tab navigation to time tracking
  src/routes/account/time-tracking.css
  src/routes/account/time-tracking.js
Labels: feature-request

#360 loot: make same tier clue scrolls stack
  src/modules/loot.js
Labels: enhancement

#361 Add 1.6.26 & 1.6.27 post
  public/img/blog/1.6.27-Release/item-outlines-new.png
  public/img/blog/1.6.27-Release/item-outlines-old.png
  public/img/blog/1.6.27-Release/website-tracker-birdhouses.png
  public/img/blog/1.6.27-Release/website-tracker-fruit-trees.png
  src/_posts/2020-09-23-10-00-1.6.27-Release.md
  src/routes/blog.scss
Labels: blog-post

#364 Lowercase config keys
  src/modules/config.js
Labels: bug
