Repository runelite/runelite.net, pull requests merged in 2020-04, with the labels that each got.

#311 Add 1.6.11 post
  public/img/blog/1.6.11-Release/ge-fuzzy-search.png
  public/img/blog/1.6.11-Release/overlay-resizing.gif
  public/img/blog/1.6.11-Release/prayer-remaining-time.png
  public/img/blog/1.6.11-Release/resize-infobox-container.gif
  src/_posts/2020-04-16-10-00-1.6.11-Release.md
Labels: blog-post

#312 Cleanup plugin hub page
  src/components/external-plugin.js
  src/components/external-plugin.scss
Labels: enhancement

#313 Show if external plugin is installed or not on plugin-hub page
  src/components/external-plugin.js
  src/modules/config.js
  src/modules/plugin-hub.js
  src/routes/plugin-hub.js
Labels: feature-request

#315 Add tags to account/ page
  src/middleware/thunk-middleware.js
  src/modules/config.js
  src/modules/item.js
  src/routes/account.js
  src/routes/account/tags.js
  src/routes/tag-show.js
  src/routes/tag.css
  src/util.js
Labels: feature-request

#317 Improve performance of item module
  src/modules/item.js
Labels: enhancement
