Repository runelite/runelite.net, pull requests merged in 2020-05, with the labels that each got.

#320 Load tags without account-based config prefix
  src/modules/config.js
  src/routes/account.js
Labels: bug

#319 Add 1.6.13 post
  public/img/blog/1.6.13-Release/divine.png
  public/img/blog/1.6.13-Release/hiscores.png
  src/_posts/2020-05-01-10-00-1.6.13-Release.md
Labels: blog-post

#322 Prevent hero image from re-rendering while scrolling
  src/components/app.js
  src/components/footer.js
  src/components/hero.js
  src/components/hero.scss
  src/components/layout.scss
  src/routes/home.scss
Labels: enhancement

#323 Update dependencies and cleanup CSS
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/components/_variables.scss
  src/components/app.scss
  src/components/feature.scss
  src/components/hero.scss
  src/components/layout.scss
  src/components/loader.css
  src/components/navigation.css
  src/components/search-bar.css
  src/components/tooltip.css
  src/modules/account.js
  src/routes/account.scss
  src/routes/account/tags.js
  src/routes/blog-show.js
  src/routes/blog.js
  src/routes/blog.scss
  src/routes/features.js
  src/routes/gh-auth-code.js
  src/routes/gh-auth-code.scss
  src/routes/home.js
  src/routes/home.scss
  src/routes/loading.js
  src/routes/loading.scss
  src/routes/logged-in.js
  src/routes/logged-in.scss
  src/routes/plugin-hub.js
  src/routes/tag-show.js
  src/routes/tag.css
  src/routes/tag.js
  src/routes/xp-show.js
  src/routes/xp-show.scss
Labels: enhancement

#324 Make all links orange
  src/components/app.scss
Labels: enhancement

#325 Add /pulse page
  src/components/app.js
  src/components/app.scss
  src/components/commit.js
  src/components/navigation.js
  src/middleware/thunk-middleware.js
  src/modules/git.js
  src/routes/blog.scss
  src/routes/pulse.js
  src/store.js
Labels: feature-request

#327 Add 1.6.14 post
  public/img/blog/1.6.14-Release/mac-gpu-rasterizer-small.png
  public/img/blog/1.6.14-Release/mac-gpu-rasterizer.png
  public/img/blog/1.6.14-Release/xp-tracker-customizable-labels.png
  src/_posts/2020-05-09-10-00-1.6.15-Release.md
Labels: blog-post

#328 Fix links to static files in blog posts
  src/blog.js
Labels: bug

#329 Add count to tooltips for pulse progress bar
  src/routes/pulse.js
Labels: enhancement

#330 Fix tooltip display when out of parent div
  src/components/layout.scss
  src/components/tooltip.css
Labels: bug

#331 Fetch bootstrap on home page
  src/routes/home.js
Labels: bug

#332 Add support for video markup to blog posts
  config-overrides.js
  package-lock.json
  package.json
  src/blog.js
  src/components/async.js
  src/markdown-loader.js
Labels: feature-request

#333 Optimize adding of `native` tag to blog links
  src/markdown-loader.js
Labels: enhancement

#334 Add combined 1.6.15/1.6.16/1.6.17 post
  public/img/blog/1.6.17-Release/clue-enemies.png
  public/img/blog/1.6.17-Release/configurable-login-screen-mirroring-is-gone.png
  public/img/blog/1.6.17-Release/configurable-login-screen.png
  public/img/blog/1.6.17-Release/configurable-overlay-background-color.png
  public/img/blog/1.6.17-Release/duplicate-chat-collapse.png
  public/img/blog/1.6.17-Release/ground-items-notify-change.png
  public/img/blog/1.6.17-Release/screen-marker-widget-snapping.gif
  public/img/blog/1.6.17-Release/transparent-menu.gif
  src/_posts/2020-05-28-10-00-1.6.17-Release.md
Labels: blog-post
