Repository runelite/runelite.net, pull requests merged in 2021-06, with the labels that each got.

#404 Add support for account/profile deletion
  src/modules/config.js
  src/routes/account.js
  src/routes/account.scss
  src/routes/account/delete.js
Labels: feature-request

#406 Rename "Accounts" to "RuneScape profiles"
  src/routes/account.js
  src/routes/account.scss
  src/routes/account/delete.js
Labels: enhancement

#408 Use URL fragment for tile markers to avoid URL limits
  src/components/app.js
  src/routes/tile-show.js
  src/routes/tile.js
Labels: bug

#409 Add 1.7.13 post
  src/_posts/2021-06-23-10-00-1.7.13-Release.md
Labels: blog-post

#410 Add support for account/tile-markers
  src/components/app.scss
  src/components/runescape-map.js
  src/modules/config.js
  src/routes/account.js
  src/routes/account/tiles.js
  src/routes/tile-show.js
Labels: feature-request

#411 Add Share buttons to /account/tags and /account/tile-markers
  src/components/app.scss
  src/routes/account/tags.js
  src/routes/account/tiles.js
Labels: enhancement

#414 Strip HTML from plugin description in plugin hub pages
  src/components/external-plugin.js
  src/modules/plugin-hub.js
Labels: bug

#415 Fix all relative links to plugin hub assets
  src/modules/plugin-hub.js
Labels: bug

#416 Fix .gif replacing when there are multiple img tags in a row
  src/modules/plugin-hub.js
Labels: bug

#417 Return 404 if external plugin was not found
  src/routes/plugin-hub-show.js
Labels: enhancement

#418 Add lock/unlock button to RuneScape map
  src/components/runescape-map.js
Labels: enhancement
