Repository runelite/runelite.net, pull requests merged in 2021-07, with the labels that each got.

#420 Switch from Explv to mejrs.github.io as map source
  src/components/runescape-map.js
  src/components/runescape-map.scss
Labels: enhancement

#421 Add plane change buttons
  src/components/runescape-map.js
Labels: feature-request

#422 Remove map locking, always add all tile markers to map
  src/components/runescape-map.js
  src/routes/account/tiles.js
Labels: enhancement

#423 Add Loading component that is shown when data are loaded
  config-overrides.js
  src/components/loading.js
  src/components/prepare.js
  src/components/runescape-map.js
Labels: enhancement

#424 Return NotFound page for missing and invalid tags and markers
  src/routes/tag-show.js
  src/routes/tile-show.js
Labels: enhancement

#425 Fix layer change buttons disabling
  src/components/runescape-map.js
Labels: bug

#428 Add additional meta tags for social media
  public/index.html
  src/components/meta.js
  src/markdown-loader.js
  src/routes/blog-show.js
  src/util.js
Labels: feature-request

#429 Add 1.7.17 post
  public/img/blog/1.7.17-Release/loot-beams.gif
  public/img/blog/1.7.17-Release/pets-chat-command.png
  src/_posts/2021-07-21-10-00-1.7.17-Release.md
Labels: blog-post

#433 Fix hash navigation
  src/index.js
Labels: bug

#434 Add nofollow to blog links
  src/markdown-loader.js
Labels: enhancement
