Repository runelite/runelite.net, pull requests merged in 2021-09, with the labels that each got.

#437 Add 1.7.22 post
  public/img/blog/1.7.22-Release/interaction-highlight.mp4
  src/_posts/2021-09-06-10-00-1.7.22-Release.md
Labels: blog-post

#438 Update platform detection code
  package-lock.json
  package.json
  src/_data/hero.js
  src/components/hero.js
  src/components/hero.scss
Labels: enhancement

#441 Update gh-auth-code with /ghauth command
  src/routes/gh-auth-code.js
Labels: bug

#442 Prevent bots from crawling download links
  src/components/hero.js
Labels: enhancement
